### ISSUE TITLE
Unicode symbols for chef and eater aren't available in any system fonts

### ISSUE THREAD

**Issue by richsilv** [tableflip/makelunch#11]
What font were you intending to render these in, @liamwooding ?

**Comment by liamwooding** [comment]
Ah, I'd naively assumed that emoji would be available in all system fonts, which I guess isn't the case for Ubuntu. I'd like for us to find a nicer font to use than the default anyway, this could be solved by using that has emoji support.

**Comment by liamwooding** [comment]
One that I like the look of a lot is [Gill Sans](https://www.myfonts.com/fonts/mti/gill-sans/), for which there are a few free alternatives. The elements around the site that do use emoji should use a font-family with emoji support
