### ISSUE TITLE
All Uploadcare images have gone missing

### ISSUE THREAD

**Issue by liamwooding** [tableflip/makelunch#16]
![screen shot 2015-07-27 at 10 53 07](https://cloud.githubusercontent.com/assets/1327356/8903159/b258e31c-344d-11e5-9166-58a214fe0acd.png)

**Comment by olizilla** [comment]
@richsilv did you tinker with this or do we need to be worried about uploadcare?

**Comment by richsilv** [comment]
Nope, I haven't touched it.
