### ISSUE TITLE
Can't update photo

### ISSUE THREAD

**Issue by olizilla** [tableflip/makelunch#8]
Tried the upload care buttons for "arbitrary link" and "upload a photo". Both seemed to succeed, but neither updated the profile photo.

**Comment by richsilv** [comment]
This is because we're trying to get an uploadcare id from the element `#uploadcare-uuid`, and it's still blank when you've uploaded a picture.  Checking why that is...

**Comment by richsilv** [comment]
...because the widget init is in a callback with the wrong name.
